name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-lint-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Lint Check (example)
      run: echo "Add ESLint or Flake8 for actual linting step"

    - name: Run Unit Tests (placeholder)
      run: echo "Add actual unit/integration test runners here"

    - name: Build All Services
      run: |
        docker-compose -f deploy/docker-compose/docker-compose.yml build

- name: Install Trivy
  run: |
    sudo apt-get install wget apt-transport-https gnupg lsb-release -y
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
    echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
    sudo apt-get update
    sudo apt-get install trivy -y

- name: Scan Built Docker Image with Trivy
  run: |
    trivy image microservices-demo/front-end:latest || true
