name: CI Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-deployed-app.com

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Apply K8s Manifests
        run: |
          kubectl apply -f deploy/kubernetes/manifests/

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          msg: "Deployment to Kubernetes completed successfully!"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
